baseURL = "https://zhengwe.com/"
languageCode = "en"
DefaultContentLanguage = "en"
enableInlineShortcodes = true
enableEmoji = true
hasCJKLanguage = true
# pagination = 10

title = "zhengwe"
author = "zheng wei"
copyright = "[Home](/) &#183; Theme [Simpleness](https://github.com/RainerChiang/simpleness) Powered by [Hugo](https://gohugo.io/)"

theme = "simpleness"
googleAnalytics = "UA-131734673-1"

[params]
  lazyImage = true
  enableMathJax = false # enable it in Front Matter
  enableReadingTime = false
  favicon = "favicon.ico"
  avatar = "favicon.png"
  startyear = "2020"
  description = "A simple Blog"
  disqus = ""

[params.valine]
  enable = false
  lang = 'en' # zh-CN
  appId = ''
  appKey = ''
  placeholder = 'Say Something......'
  requiredFields = ['nick', 'mail']
  avatar = 'favicon.ico'
  visitor = true
  enableHeaderVisitor = true
  debug = true

[menu]
  [[menu.main]]
  name = "Home"
  url = "/"
  weight = 1
#  [[menu.main]]
#  name = "Tag"
#  url = "/tag/"
#  weight = 2
  [[menu.main]]
  name = "About"
  url = "/about/"
  weight = 3

[social]
  github = "https://github.com/zhengwe"
  rss = "index.xml"

[taxonomies]
category = "categories"
tag = "tags"

# doc: https://gohugo.io/getting-started/configuration-markup#highlight
# syntax style: https://xyproto.github.io/splash/docs/longer/all.html
[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = "monokai" # github, dracula, vim, monokai
    tabWidth = 4
